name: createartifacts
on: 
  push:
    branches: 
       - "main"
       - "!Features/*"
  workflow_dispatch: 
  schedule:
   - cron: "0 1 * * *"   
env:
  FileName: Sachin
jobs:
    createart:
        runs-on: ubuntu-latest
        steps:
         - name: Create Artifacts 
           run: echo This is username ${{ vars.Username }} and password encrypted ${{secrets.password}} > $FileName.txt
         - name: Display Files
           run: cat $FileName.txt
                    