name: createartifacts
on: push

jobs:
    createart:
        runs-on: ubuntu-latest
        steps:
         - name: Create Artifacts 
           run: echo "This is first part" + ${{ vars.Username }} + "" + ${{secrets.password}} > sachin.txt
         